export const banks = [
    { code: "001", name: "Banco do Brasil S.A." },
    { code: "033", name: "Banco Santander (Brasil) S.A." },
    { code: "104", name: "Caixa Econômica Federal" },
    { code: "237", name: "Banco Bradesco S.A." },
    { code: "341", name: "Itaú Unibanco S.A." },
    { code: "260", name: "Nu Pagamentos S.A." },
    { code: "077", name: "Banco Inter S.A." },
    { code: "336", name: "Banco C6 S.A." },
    { code: "079", name: "PicPay Bank" },
    { code: "290", name: "PagSeguro Internet S.A." },
    { code: "380", name: "PicPay Serviços" },
    { code: "212", name: "Banco Original S.A." },
    { code: "422", name: "Banco Safra S.A." },
    { code: "208", name: "Banco BTG Pactual S.A." },
    { code: "748", name: "Banco Cooperativo Sicredi S.A." },
    { code: "756", name: "Banco Cooperativo do Brasil S.A. - BANCOOB" },
    { code: "655", name: "Banco Votorantim S.A." },
    { code: "477", name: "Citibank N.A." },
    { code: "041", name: "Banco do Estado do Rio Grande do Sul S.A." },
    { code: "004", name: "Banco do Nordeste do Brasil S.A." },
    { code: "021", name: "BANESTES S.A. Banco do Estado do Espírito Santo" },
    { code: "085", name: "Cooperativa Central de Crédito Ailos" },
    { code: "403", name: "Banco Cora SCD S.A." },
    { code: "637", name: "Banco Sofisa S.A." },
    { code: "197", name: "Stone Pagamentos S.A." },
    { code: "102", name: "XP Investimentos CCTVM S.A." },
    { code: "323", name: "Mercado Pago IP Ltda." },
    { code: "070", name: "BRB - Banco de Brasília S.A." },
    { code: "121", name: "Banco Agibank S.A." },
    { code: "505", name: "Banco Credit Suisse (Brasil) S.A." },
    { code: "604", name: "Banco Industrial do Brasil S.A." },
    { code: "479", name: "Banco ItauBank S.A." },
    { code: "074", name: "Banco J. Safra S.A." },
    { code: "218", name: "Banco BS2 S.A." },
    { code: "069", name: "BPN Brasil Banco Múltiplo S.A." },
    { code: "012", name: "Banco INBURSA de Investimentos S.A." },
    { code: "246", name: "Banco ABC Brasil S.A." },
    { code: "224", name: "Banco da China Brasil S.A." },
    { code: "243", name: "Banco Máxima S.A." },
    { code: "222", name: "Banco Credit Agricole Brasil S.A." },
    { code: "707", name: "Banco Daycoval S.A." },
    { code: "024", name: "Banco BANDEPE S.A." },
    { code: "037", name: "Banco do Estado do Pará S.A." },
    { code: "003", name: "Banco da Amazônia S.A." },
    { code: "047", name: "Banco do Estado de Sergipe S.A." },
    { code: "136", name: "Unicred Servidores" },
    { code: "364", name: "Gerencianet S.A." },
    { code: "299", name: "Banco Omni S.A." },
    { code: "461", name: "Asaas Gestão Financeira Instituição de Pagamento S.A." },
    { code: "318", name: "Banco BMG S.A." }
].sort((a, b) => Number(a.code) - Number(b.code));
